// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// City is the predicate function for city builders.
type City func(*sql.Selector)

// File is the predicate function for file builders.
type File func(*sql.Selector)

// Otp is the predicate function for otp builders.
type Otp func(*sql.Selector)

// SiteDetail is the predicate function for sitedetail builders.
type SiteDetail func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
